apiVersion: apps/v1 # Describes the version of the Kubernetes API
kind: Deployment
metadata:
  name: devops-python
  labels:
    app: devops-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-python
  template:
    metadata:
      labels:
        app: devops-python
    spec:
      containers:
        - name: devops-python
          image: "lucasmelin/devops-python-example:v0"
          imagePullPolicy: Never
          env:
          - name: REDIS_URL
            value: redis.default.svc.cluster.local
          - name: GET_HOSTS_FROM
            value: dns
          ports:
          - containerPort: 8080
