apiVersion: v1 # Describes the version of the Kubernetes API
kind: Service
metadata:
  name: devops-python
  labels:
    app: devops-python
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: devops-python