# Generated by Django 2.1.2 on 2018-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='date_time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='weather',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
