# Generated by Django 2.1.2 on 2018-10-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measurement', models.CharField(choices=[('KGPY', 'Kilograms per person, per year'), ('LPY', 'Litres per person, per year')], default='KGPY', max_length=4)),
                ('scalar_factor', models.CharField(choices=[('U', 'Units'), ('K', 'Thousands')], default='U', max_length=1)),
                ('food_category', models.CharField(choices=[('FA', 'Food available'), ('FAFL', 'Food available, adjusted for loss')], default='FA', max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
