# Generated by Django 2.1.2 on 2018-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='coordinate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dguid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commodity',
            name='geo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commodity',
            name='ref_date',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='commodity',
            name='scalar_id',
            field=models.IntegerField(choices=[(0, 0), (3, 3)], default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='commodity',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commodity',
            name='unit_of_measurement_id',
            field=models.IntegerField(choices=[('194', '194'), ('205', '205')], default='194'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='vector',
            field=models.CharField(default='', max_length=10),
        ),
    ]
