# Generated by Django 2.1.2 on 2018-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20181023_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='decimals',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='symbol',
            field=models.CharField(default='', max_length=2),
        ),
    ]
